name: C Compilar y Ejecutar

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compilar
    - run: gcc *.c
    - name: ejecutar
    - run: ./series